# _config.yml
title: My Simple Jekyll Site
email: your-email@example.com # Замените на свой email
description: >-
  Welcome to my simple Jekyll site!
baseurl: ""
url: "https://di-ivi19.github.io/" # Убедитесь, что это ваш URL

# Build settings
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Navigation
header_pages:
  - index.md
  - services.md
  - work.md
  - about.md
  - contact.md

# Collections
collections:
  works:
    output: true
    permalink: /work/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"



# Exclude from processing
exclude:
  - README.md
  - Mobile
  - docs/
  - vendor/
  - Gemfile
  - Gemfile.lock
