# _config.yml
title: My Simple Jekyll Site
email: your-email@example.com # Замените на свой email
description: >-
  Welcome to my simple Jekyll site!
baseurl: ""
url: "https://di-ivi19.github.io/pages23" # Убедитесь, что это ваш URL

# Выбираем официальную тему для GitHub Pages
theme: jekyll-theme-architect

plugins:
  - jekyll-feed
